apiVersion: v1
kind: Service
metadata:
  name: netflix-service
  namespace: default
  labels:
    app: netflix
spec:
  type: NodePort
  selector:
    app: netflix
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  sessionAffinity: ClientIP
